config/routes.rb
module Spacekraft
	class RouteConstraint
		def self.matches?( request )
			not request.subdomain.present? or request.subdomain == 'www'
		end
	end
end

Spacekraft::Application.routes.draw do

  resources :sk_modules

	constraints( Spacekraft::RouteConstraint ) do
		devise_for :users

		get "dashboard/index", :as => :dashboard

		resources :discussions
		resources :groups do
			resources :discussions
		end

		root :to => 'pages#index'
	end

end

app/models/commune.rb
class Commune

	include Jabber


	def new( user )
		@user   = user
		@jid    = JID::new( "#{user.id}@localhost" )
		@client = Client.new( @jid )

		@client.connect( 'localhost', 5222 )
		@client.auth( 'password' )
		self
	end


	def register
		@client.register(
			'password', {
			'name'  => 'commune'
		} )
		@client.auth( 'password' )
		self
	end

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base

	belongs_to :group

end

app/models/group.rb
class Group < ActiveRecord::Base

	has_many :discussions

end

app/models/sk_module.rb
class SkModule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	# User authentication
	devise :database_authenticatable, :registerable, :token_authenticatable, :recoverable, :rememberable # :confirmable, :lockable, :timeoutable,:trackable, :validatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :remember_me

	# Create a user on the XMPP server after a user is created in Rails
	after_create :create_commune


	private # =====================================


	def create_commune
		@commune = Commune.new( self ).register
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	include UrlHelper

	protect_from_forgery

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

	def index
		@discussions = Discussion.all
	end


	def show
		@discussion = Discussion.find( params[:id] )
	end


	def new
		@discussion = Discussion.new
		@groups = Group.all
	end


	def edit
		@discussion = Discussion.find( params[:id] )
	end


	def create
		@discussion = Discussion.new( params[:discussion] )

		if @discussion.save
			redirect_to( @discussion, :notice => 'Discussion was successfully created.' )
		else
			render :action => "new"
		end
	end


	def update
		@discussion = Discussion.find( params[:id] )

		if @discussion.update_attributes( params[:discussion] )
			redirect_to( @discussion, :notice => 'Discussion was successfully updated.' )
		else
			render :action => "edit"
		end
	end


	def destroy
		@discussion = Discussion.find( params[:id] )
		@discussion.destroy
		redirect_to( discussions_url )
	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end

end

app/controllers/sk_modules_controller.rb
class SkModulesController < ApplicationController
  # GET /sk_modules
  # GET /sk_modules.xml
  def index
    @sk_modules = SkModule.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sk_modules }
    end
  end

  # GET /sk_modules/1
  # GET /sk_modules/1.xml
  def show
    @sk_module = SkModule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sk_module }
    end
  end

  # GET /sk_modules/new
  # GET /sk_modules/new.xml
  def new
    @sk_module = SkModule.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sk_module }
    end
  end

  # GET /sk_modules/1/edit
  def edit
    @sk_module = SkModule.find(params[:id])
  end

  # POST /sk_modules
  # POST /sk_modules.xml
  def create
    @sk_module = SkModule.new(params[:sk_module])

    respond_to do |format|
      if @sk_module.save
        format.html { redirect_to(@sk_module, :notice => 'Sk module was successfully created.') }
        format.xml  { render :xml => @sk_module, :status => :created, :location => @sk_module }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sk_module.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sk_modules/1
  # PUT /sk_modules/1.xml
  def update
    @sk_module = SkModule.find(params[:id])

    respond_to do |format|
      if @sk_module.update_attributes(params[:sk_module])
        format.html { redirect_to(@sk_module, :notice => 'Sk module was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sk_module.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sk_modules/1
  # DELETE /sk_modules/1.xml
  def destroy
    @sk_module = SkModule.find(params[:id])
    @sk_module.destroy

    respond_to do |format|
      format.html { redirect_to(sk_modules_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sk_modules_helper.rb
module SkModulesHelper
end

app/helpers/url_helper.rb
module UrlHelper

	def with_subdomain( subdomain )
		subdomain = ( subdomain || '' )
		subdomain += '.' unless subdomain.empty?
		[subdomain, request.domain, request.port_string].join
	end


	def url_for( options = nil )
		if options.kind_of?( Hash ) && options.has_key?( :subdomain )
			options[:host] = with_subdomain( options.delete( :subdomain ) )
		end

		super
	end

end


module Cell
	class Rails < AbstractController::Base
		include ActionController::UrlFor
		include UrlHelper
	end
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/discussions/_form.html.erb
<%= form_for( @discussion ) do | f | %>

	<% if @discussion.errors.any? %>

		<div id="error_explanation">
			<h2><%= pluralize( @discussion.errors.count, "error" ) %> prohibited this discussion from being saved:</h2>

			<ul>
			<% @discussion.errors.full_messages.each do | msg | %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>

	<% end %>


	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</div>


	<div class="field">
		<%= f.label :content %><br />
		<%= f.text_area :content %>
	</div>


	<div class="field">
		<%= f.label :group %><br />
		<%= f.collection_select( :group, @groups, :id, :name ) %>
	</div>


	<div class="actions">
		<%= f.submit %>
	</div>


<% end %>

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<h1>Listing discussions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @discussions.each do |discussion| %>
  <tr>
    <td><%= discussion.title %></td>
    <td><%= discussion.content %></td>
    <td><%= discussion.group %></td>
    <td><%= link_to 'Show', discussion %></td>
    <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
    <td><%= link_to 'Destroy', discussion, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Discussion', new_discussion_path %>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form' %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @discussion.title %>
</p>

<p>
  <b>Content:</b>
  <%= @discussion.content %>
</p>

<p>
  <b>Group:</b>
  <%= @discussion.group %>
</p>


<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', discussions_path %>

app/views/groups/_form.html.erb
<%= form_for( @group ) do |f| %>

	<% if @group.errors.any? %>

		<div id="error_explanation">
			<h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

			<ul>
				<% @group.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>

	<% end %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.description %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>


<p>
  <b>Description:</b>
  <%= @group.description %>
</p>


<p>
  <b>Discussions:</b>
	<ul>
		<% @group.discussions.each do | disc | %>
			<li><%= link_to disc.title, disc %></li>
		<% end %>
	</ul>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.haml
%html

	%head
		%title Spacekraft
		= stylesheet_link_tag :all
		= javascript_include_tag :defaults
		= csrf_meta_tag

	%body

		%div#page

			%div.container

				%div#header.span-24
					= render_cell :menu, :secondary
					= render_cell :menu, :module
					= render_cell :menu, :primary

				%div#main.span-16

					= yield

				%div#sidebar.span-7
					%h2 Sidebar

app/views/pages/index.html.haml
%h1 SpaceKraft

%div
	%p
		Welcome to SpaceKraft!
		You need to login to use this application.

app/views/sk_modules/_form.html.erb
<%= form_for(@sk_module) do |f| %>
  <% if @sk_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sk_module.errors.count, "error") %> prohibited this sk_module from being saved:</h2>

      <ul>
      <% @sk_module.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subdomain %><br />
    <%= f.text_field :subdomain %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br />
    <%= f.check_box :enabled %>
  </div>
  <div class="field">
    <%= f.label :machine_name %><br />
    <%= f.text_field :machine_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sk_modules/edit.html.erb
<h1>Editing sk_module</h1>

<%= render 'form' %>

<%= link_to 'Show', @sk_module %> |
<%= link_to 'Back', sk_modules_path %>

app/views/sk_modules/index.html.erb
<h1>Listing sk_modules</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Subdomain</th>
    <th>Enabled</th>
    <th>Machine name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sk_modules.each do |sk_module| %>
  <tr>
    <td><%= sk_module.name %></td>
    <td><%= sk_module.subdomain %></td>
    <td><%= sk_module.enabled %></td>
    <td><%= sk_module.machine_name %></td>
    <td><%= link_to 'Show', sk_module %></td>
    <td><%= link_to 'Edit', edit_sk_module_path(sk_module) %></td>
    <td><%= link_to 'Destroy', sk_module, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sk module', new_sk_module_path %>

app/views/sk_modules/new.html.erb
<h1>New sk_module</h1>

<%= render 'form' %>

<%= link_to 'Back', sk_modules_path %>

app/views/sk_modules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sk_module.name %>
</p>

<p>
  <b>Subdomain:</b>
  <%= @sk_module.subdomain %>
</p>

<p>
  <b>Enabled:</b>
  <%= @sk_module.enabled %>
</p>

<p>
  <b>Machine name:</b>
  <%= @sk_module.machine_name %>
</p>


<%= link_to 'Edit', edit_sk_module_path(@sk_module) %> |
<%= link_to 'Back', sk_modules_path %>